 const ItemList = [
    {
      key: 1,
      title: "Blooming Bear Planter",
      img: "/public/images/bear.jpg",
      description:"“A playful home for your greens, handcrafted from coconut shell.",
      price: 100,
    },
    {
      key: 2,
      title: "Coconut Hoop Earrings",
      img: "/public/images/circle earring.jpg", 

      description:"Bold, circular elegance carved straight from nature.",
      price: 100,
    },
    {
      key: 3,
      title: "Tribal Dot Circle Earrings",
img: "/public/images/circle with dots earring.jpg",  
description:"Earthy dots meet heritage design in this boho-inspired pair.",    
price: 100,
    },
    {
      key: 4,
      title: "Floral Circle Drop Earrings",
img: "/public/images/circle with flower earring.jpg", 
description:"A blooming twist on the classic drop — light, lovely, and natural.",     
price: 100,
    },
    {
      key: 5,
      title: "Rustic Diya Candle Holder",
      img: "/public/images/diya2.jpg",     
      description:"Bring home the glow of tradition with this hand-carved diya.", 
      price: 100,
    },
    {
      key: 6,
      title: "Majestic Elephant Showpiece",
      img: "/public/images/elephant2.jpg",     
      description:"Symbol of wisdom and strength, lovingly shaped from coconut shell.", 
      price: 100,
    },
    {
      key: 7,
      title: "Petal Charm Earring & Locket Set",
      img: "/public/images/flower earring with locket.jpg", 
      description:"A delicate set inspired by nature’s grace — lightweight and stunning.",    
      price: 100,
    },
    {
      key: 8,
      title: "Coconut Bowl with Lid & Spoon",
      img: "/public/images/katora with lid and spoon.jpg",   
      description:"Perfect for condiments or dry storage — eco-luxury at its finest.",    
      price: 100,
    },
    {
      key: 9,
      title: "Classic Lid Bowl",
      img: "/public/images/katora with lid2.jpg",
      description:"Minimalist and functional — nature’s storage solution.",
      price: "100",
    },
    {
      key: 10,
      title: "Leaf Drop Set – Earring & Pendant",
      img: "/public/images/leaf earring with locket.jpg",
      description:"Wear a touch of the forest with this matching leaf duo.",
      price: "100",
    },
    {
      key: 11,
      title: "Minimal Leaf Earrings",
      img: "/public/images/leaf earring.jpg",
      description:"Simple. Sustainable. Stylish.",
      price: "100",
    },
    {
      key: 12,
      title: "Turtle Trinket Figurine",
      img: "/public/images/turtle.jpg",
      description:"A slow and steady reminder of peace, carved from coconut shell.",
      price: "100",
    },
    {
      key: 13,
      title: "Graceful Swan & Leaf Showpiece",
      img: "/public/images/swan with leaf.jpg",
      description:"A fusion of art and nature — elegant decor in earthy tones.",
      price: "100",
    },
    {
      key: 14,
      title: "Eco Pen Stand",
      img: "/public/images/pen stand.jpg",
      description:"For desks that deserve a natural touch.",
      price: "100",
    },
    {
      key: 15,
      title: "Round Leaf Keychain",
      img: "/public/images/round leaf key chain.jpg",
      description:"Carry calm and coconut-crafted charm in your pocket.",
      price: "100",
    },
    {
      key: 16,
      title: "Boho Triangle Earrings",
      img: "/public/images/triangle earring.jpg",
      description:"Sharp lines. Soft vibes. Earth-forward fashion.",
      price: "100",
    },
    {
      key: 17,
      title: "Raw Rectangle Earrings",
      img: "/public/images/rectangle earring.jpg",
      description:"Geometric charm meets organic soul.",
      price: "100",
    },
    {
      key: 18,
      title: "Natural Soap Tray",
      img: "/public/images/soap3.jpg",
      description:"Keep it clean and green with this coconut shell soap holder.",
      price: "100",
    },
    {
      key: 19,
      title: "Earthy Leaf Keychain",
      img: "/public/images/leaf key chain.jpg",
      description:"Nature’s vibe, always with you.",
      price: "100",
    },
  ];

export default ItemList;