 const ItemList = [
    {
      key: 1,
      title: "Blooming Bear Planter",
      img: "/images/bear.jpg",
      description:"“A playful home for your greens, handcrafted from coconut shell.",
      price: 499,
    },
    {
      key: 2,
      title: "Coconut Hoop Earrings",
      img: "/images/circle earring.jpg", 

      description:"Bold, circular elegance carved straight from nature.",
      price: 149,
    },
    {
      key: 3,
      title: "Tribal Dot Circle Earrings",
img: "/images/circle with dots earring.jpg",  
description:"Earthy dots meet heritage design in this boho-inspired pair.",    
price: 149,
    },
    {
      key: 4,
      title: "Floral Circle Drop Earrings and Locket Set",
img: "/images/circle with flower earring.jpg", 
description:"A blooming twist on the classic drop — light, lovely, and natural.",     
price: 199,
    },
    {
      key: 5,
      title: "Rustic Diya Candle Holder",
      img: "/images/diya2.jpg",     
      description:"Bring home the glow of tradition with this hand-carved diya.", 
      price: 299,
    },
    {
      key: 6,
      title: "Majestic Elephant Showpiece",
      img: "/images/elephant2.jpg",     
      description:"Symbol of wisdom and strength, lovingly shaped from coconut shell.", 
      price: 899,
    },
    {
      key: 7,
      title: "Petal Charm Earring & Locket Set",
      img: "/images/flower earring with locket.jpg", 
      description:"A delicate set inspired by nature’s grace — lightweight and stunning.",    
      price: 249,
    },
    {
      key: 8,
      title: "Coconut Bowl with Lid & Spoon",
      img: "/images/katora with lid and spoon.jpg",   
      description:"Perfect for condiments or dry storage — eco-luxury at its finest.",    
      price: 699,
    },
    // {
    //   key: 9,
    //   title: "Classic Lid Bowl",
    //   img: "/images/katora with lid2.jpg",
    //   description:"Minimalist and functional — nature’s storage solution.",
    //   price: 100,
    // },
    {
      key: 10,
      title: "Leaf Drop Set – Earring & Pendant",
      img: "/images/leaf earring with locket.jpg",
      description:"Wear a touch of the forest with this matching leaf duo.",
      price: 199,
    },
    {
      key: 11,
      title: "Minimal Leaf Earrings",
      img: "/images/leaf earring.jpg",
      description:"Simple. Sustainable. Stylish.",
      price: 149,
    },
    {
      key: 12,
      title: "Turtle Trinket Figurine",
      img: "/images/turtle.jpg",
      description:"A slow and steady reminder of peace, carved from coconut shell.",
      price: 699,
    },
    {
      key: 13,
      title: "Graceful Swan & Leaf Showpiece",
      img: "/images/swan with leaf.jpg",
      description:"A fusion of art and nature — elegant decor in earthy tones.",
      price: 499,
    },
    {
      key: 14,
      title: "Eco Bear Pen Stand",
      img: "/images/pen stand.jpg",
      description:"For desks that deserve a natural touch.",
      price: 249,
    },
    {
      key: 15,
      title: "Round Leaf Keychain",
      img: "/images/round leaf key chain.jpg",
      description:"Carry calm and coconut-crafted charm in your pocket.",
      price: 149,
    },
    {
      key: 16,
      title: "Boho Triangle Earrings",
      img: "/images/triangle earring.jpg",
      description:"Sharp lines. Soft vibes. Earth-forward fashion.",
      price: 149,
    },
    {
      key: 17,
      title: "Raw Rectangle Earrings",
      img: "/images/rectangle earring.jpg",
      description:"Geometric charm meets organic soul.",
      price: 149,
    },
    {
      key: 18,
      title: "Natural Soap Tray",
      img: "/images/soap3.jpg",
      description:"Keep it clean and green with this coconut shell soap holder.",
      price: 199,
    },
    {
      key: 19,
      title: "Earthy Leaf Keychain",
      img: "/images/leaf key chain.jpg",
      description:"Nature’s vibe, always with you.",
      price: 149,
    },
  ];

export default ItemList;